# Configuration Nixpacks pour le backend
[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
dependsOn = ["setup"]
# Utiliser npm install au lieu de npm ci car pas de package-lock.json local
cmds = ["npm install --production=false"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"