[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x", "bash"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["bash scripts/build-railway.sh"]

[start]
cmd = "cd apps/backend && npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_LOGLEVEL = "error"