[build]
builder = "nixpacks"
buildCommand = "cd apps/backend && npm run build"

[deploy]
startCommand = "cd apps/backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.services]]
name = "backend"