[build]
builder = "nixpacks"
buildCommand = "cd apps/backend && rm -rf dist && npm run build"

[deploy]
startCommand = "cd apps/backend && npm run start:production"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10